#pragma config(Sensor, S3,     colourBlind,    sensorCOLORFULL)
#pragma config(Sensor, S4,     sonu,           sensorSONAR)
#pragma config(Motor,  motorB,          B,             tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorC,          C,             tmotorNXT, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while(true)
	{
   while(SensorValue[sonu] >= 27)   // While the Sonar Sensor readings are less than the specified, 'distance_in_cm':
   {
     motor[motorB]=50;
  	 motor[motorC]=50;
   }
   while(SensorValue[sonu] <= 27)
 {  motor[motorB]=50;
  	 motor[motorC]=-20;
  }
 while (SensorValue[sonu] >= 130)
  { motor[motorB]=-20;
  	 motor[motorC]=50;
}
}
}
