#pragma config(Sensor, S3,     colourBlind,    sensorCOLORFULL)
#pragma config(Sensor, S4,     sonu,           sensorSONAR)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//


task main()
{
while(true)
  {
  int distance_in_cm = 50	;   // Create variable 'distance_in_cm' and initialize it to 20(cm).

   if(SensorValue[sonu] > 70||SensorValue[sonu]<150)   // While the Sonar Sensor readings are less than the specified, 'distance_in_cm':
   {
      motor[motorB] = 20;                     // Motor B is run at a 75 power level
      motor[motorC] = 90;                     // Motor C is run at a 75 power level
       wait1Msec(500);
   }
  else if(SensorValue[sonu] > 30||SensorValue[sonu]<40)
   {
	 motor[motorB] = 75;
   motor[motorC] = 75;
   wait1Msec(500);
   }
   else if(SensorValue[sonu] < 30)
   {
	 motor[motorB] = 75;
   motor[motorC] = 75;
   wait1Msec(500);
   }
}
}
