#pragma config(Sensor, S1,     sonar,          sensorSONAR)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
  int values;
  for(;1 ;)
  {
   values=SensorValue(sonar);
   nxtDisplayTextLine(4,"2sonar=%d",values);
  if ( values>32)
   {
     motor [motorB]=-100;
     motor [motorA]=-10;
     wait1Msec (100);
     motor[motorB]=-50;
     motor[motorA]=-50;
     wait1Msec (20);
     motor [motorB]=-10;
     motor [motorA]=-100;
     wait1Msec (50);
     continue;
    }
   else if (values<30)
    {
     motor [motorA]=-90;
     motor [motorB]=-10;
     wait1Msec (100);
     motor[motorA]=-50;
     motor[motorB]=-50;
     wait1Msec (20);
     motor [motorB]=-90;
     motor [motorA]=-10;
     wait1Msec (50);
     continue;
     }
   }
   }
