#pragma config(Sensor, S4,     sonar,          sensorSONAR)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{

while(true)
{
  	 motor[motorC]=50;
  	 motor[motorC]=50;

  }


}
